### ISSUE TITLE
想问一下 compute_discontinuous_f1 这个函数是计算哪种f1的呀

### ISSUE THREAD

**Issue by xuanzebi** [daixiangau/naacl2019-select-pretraining-data-for-ner#1]
![image](https://user-images.githubusercontent.com/26642184/63911474-eb00a200-ca5c-11e9-8843-806190dfc862.png)

然后想想问一下，如果最后一层没有用CRF，那么标签B后边就不一定跟着I标签，那这种该怎么计算f1呀。因为我看代码里计算f1，都是先把实体找出来，不知道有没有不用crf层计算f1的函数呢

谢谢~

**Comment by dainlp** [comment]
1. utils里的代码是不同项目公用的，这篇NAACL paper里没有用到这个函数应该。
我另一篇paper里有discontinuous entity mention 的例子：https://aclweb.org/anthology/P18-3006
这个函数就是只计算这部分discontinuous mentions的。
2. 我这里写的ner的evaluation都是基于mention level的，如果用sequence tagging method的话，需要把BIO转换成mention，你说的B后面没跟着I标签，或者I前面不是B的，可以用一些简单的rule转换这些tag，然后再提取成mentions。

**Comment by xuanzebi** [comment]
好的 谢谢 ~

大佬太强了
