### ISSUE TITLE
你好 想问一下 你是词向量、预训练、charcter-embedding是如何对齐的

### ISSUE THREAD

**Issue by xuanzebi** [daixiangau/naacl2019-select-pretraining-data-for-ner#2]
![image](https://user-images.githubusercontent.com/26642184/64665201-43379b00-d484-11e9-9f5f-19e0d94bc2c1.png)

比如 使用elmo 是 1024 维，glove 是300维，然后charter-embedding又是假如100维

想问一下是怎么处理的 是直接拼接吗 还是怎么

最后对齐到多少维输入给下一层

**Comment by dainlp** [comment]
是的，concatenate，拼接。你举得例子的话，一个word就对应一个1424-d vector.

**Comment by xuanzebi** [comment]
好的 

这样拼接的话 楼主有对比过其他的方法吗。感觉这样的话 1000多维度是不是有点太多了。

**Comment by dainlp** [comment]
只瞎试过简单的把1024 project到100，然后跟pretrained word vector （也是100-d）sum或者avg。没啥明显区别。

**Comment by xuanzebi** [comment]
好滴 谢谢~
